ALTER TABLE indicator_btc ADD COLUMN tr NUMERIC NULL;
ALTER TABLE indicator_eth ADD COLUMN tr NUMERIC NULL;
ALTER TABLE indicator_sol ADD COLUMN tr NUMERIC NULL;
ALTER TABLE indicator_bnb ADD COLUMN tr NUMERIC NULL;
ALTER TABLE indicator_trump ADD COLUMN tr NUMERIC NULL;
