CREATE TABLE IF NOT EXISTS data_btc_1h PARTITION OF data_btc FOR VALUES IN ('1h');
CREATE TABLE IF NOT EXISTS data_btc_4h PARTITION OF data_btc FOR VALUES IN ('4h');
CREATE TABLE IF NOT EXISTS data_btc_1d PARTITION OF data_btc FOR VALUES IN ('1d');
CREATE TABLE IF NOT EXISTS data_btc_1w PARTITION OF data_btc FOR VALUES IN ('1w');
CREATE TABLE IF NOT EXISTS data_btc_1m PARTITION OF data_btc FOR VALUES IN ('1m');

CREATE TABLE IF NOT EXISTS data_eth_1h PARTITION OF data_eth FOR VALUES IN ('1h');
CREATE TABLE IF NOT EXISTS data_eth_4h PARTITION OF data_eth FOR VALUES IN ('4h');
CREATE TABLE IF NOT EXISTS data_eth_1d PARTITION OF data_eth FOR VALUES IN ('1d');
CREATE TABLE IF NOT EXISTS data_eth_1w PARTITION OF data_eth FOR VALUES IN ('1w');
CREATE TABLE IF NOT EXISTS data_eth_1m PARTITION OF data_eth FOR VALUES IN ('1m');

CREATE TABLE IF NOT EXISTS data_sol_1h PARTITION OF data_sol FOR VALUES IN ('1h');
CREATE TABLE IF NOT EXISTS data_sol_4h PARTITION OF data_sol FOR VALUES IN ('4h');
CREATE TABLE IF NOT EXISTS data_sol_1d PARTITION OF data_sol FOR VALUES IN ('1d');
CREATE TABLE IF NOT EXISTS data_sol_1w PARTITION OF data_sol FOR VALUES IN ('1w');
CREATE TABLE IF NOT EXISTS data_sol_1m PARTITION OF data_sol FOR VALUES IN ('1m');

CREATE TABLE IF NOT EXISTS data_bnb_1h PARTITION OF data_bnb FOR VALUES IN ('1h');
CREATE TABLE IF NOT EXISTS data_bnb_4h PARTITION OF data_bnb FOR VALUES IN ('4h');
CREATE TABLE IF NOT EXISTS data_bnb_1d PARTITION OF data_bnb FOR VALUES IN ('1d');
CREATE TABLE IF NOT EXISTS data_bnb_1w PARTITION OF data_bnb FOR VALUES IN ('1w');
CREATE TABLE IF NOT EXISTS data_bnb_1m PARTITION OF data_bnb FOR VALUES IN ('1m');

CREATE TABLE IF NOT EXISTS data_trump_1h PARTITION OF data_trump FOR VALUES IN ('1h');
CREATE TABLE IF NOT EXISTS data_trump_4h PARTITION OF data_trump FOR VALUES IN ('4h');
CREATE TABLE IF NOT EXISTS data_trump_1d PARTITION OF data_trump FOR VALUES IN ('1d');
CREATE TABLE IF NOT EXISTS data_trump_1w PARTITION OF data_trump FOR VALUES IN ('1w');
CREATE TABLE IF NOT EXISTS data_trump_1m PARTITION OF data_trump FOR VALUES IN ('1m');

