ALTER TABLE data_btc ADD COLUMN is_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE data_eth ADD COLUMN is_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE data_sol ADD COLUMN is_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE data_bnb ADD COLUMN is_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE data_trump ADD COLUMN is_complete BOOLEAN DEFAULT FALSE;