DROP TABLE IF EXISTS data_btc_1h;
DROP TABLE IF EXISTS data_btc_4h;
DROP TABLE IF EXISTS data_btc_1d;

DROP TABLE IF EXISTS data_eth_1h;
DROP TABLE IF EXISTS data_eth_4h;
DROP TABLE IF EXISTS data_eth_1d;

DROP TABLE IF EXISTS data_sol_1h;
DROP TABLE IF EXISTS data_sol_4h;
DROP TABLE IF EXISTS data_sol_1d;

DROP TABLE IF EXISTS data_bnb_1h;
DROP TABLE IF EXISTS data_bnb_4h;
DROP TABLE IF EXISTS data_bnb_1d;

DROP TABLE IF EXISTS data_trump_1h;
DROP TABLE IF EXISTS data_trump_4h;
DROP TABLE IF EXISTS data_trump_1d;