ALTER TABLE data_btc ADD COLUMN trend NUMERIC;
ALTER TABLE data_eth ADD COLUMN trend NUMERIC;
ALTER TABLE data_sol ADD COLUMN trend NUMERIC;
ALTER TABLE data_bnb ADD COLUMN trend NUMERIC;
ALTER TABLE data_trump ADD COLUMN trend NUMERIC;